# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17EWHNDDcHUrDeSBS6dseBrSZhcjnj5n1
"""

import pandas as pd
import pyodbc
import pysftp
import sqlalchemy

data = """
{
    "0":{
        "fec_alta": "11/01/2022",
        "user_name": "JoseMario",
        "codigo_zip": "89421",
        "credit_card_num": "1234987124123",
        "credit_card_ccv": "123",
        "cuenta_numero": "4123412380",
        "direccion": "CAlle24#82",
        "geo_latitud": "000",
        "geo_longitud": "000",
        "color_favorito": "rojo",
        "foto_dni": "N/A",
        "ip": "90.90.90.123",
        "auto": "mercedes",
        "auto_modelo": "1",
        "auto_tipo": "convertible",
        "auto_color": "rojo",
        "cantidad_compras_realizadas": 84978,
        "avatar": "https://cdn.fakercloud.com/avatars/muringa_128.jpg",
        "fec_birthday": "2022-03-28T21:18:02.439Z",
        "id": "1"
    },
    "1":{
        "fec_alta": "2021-07-31T00:11:06.741Z",
        "user_name": "Junior39",
        "codigo_zip": "22139",
        "credit_card_num": "6767-2293-4172-5169",
        "credit_card_ccv": "357",
        "cuenta_numero": "50099904",
        "direccion": "Amelia Forks",
        "geo_latitud": "-40.0728",
        "geo_longitud": "-39.5073",
        "color_favorito": "white",
        "foto_dni": "http://placeimg.com/640/480",
        "ip": "224.140.175.223",
        "auto": "Bugatti Corvette",
        "auto_modelo": "Challenger",
        "auto_tipo": "Cargo Van",
        "auto_color": "Lamborghini PT Cruiser",
        "cantidad_compras_realizadas": 30564,
        "avatar": "https://cdn.fakercloud.com/avatars/franciscoamk_128.jpg",
        "fec_birthday": "2022-03-29T03:28:16.364Z",
        "id": "2"
    },
    "2":{
        "fec_alta": "2021-10-24T02:30:07.389Z",
        "user_name": "Ethelyn.Schinner",
        "codigo_zip": "41351",
        "credit_card_num": "3731-257378-42633",
        "credit_card_ccv": "406",
        "cuenta_numero": "38047405",
        "direccion": "Shaniya Springs",
        "geo_latitud": "10.3752",
        "geo_longitud": "-105.7502",
        "color_favorito": "gold",
        "foto_dni": "http://placeimg.com/640/480",
        "ip": "190.130.230.168",
        "auto": "Volkswagen Cruze",
        "auto_modelo": "Model S",
        "auto_tipo": "Hatchback",
        "auto_color": "Jaguar Camaro",
        "cantidad_compras_realizadas": 68331,
        "avatar": "https://cdn.fakercloud.com/avatars/yigitpinarbasi_128.jpg",
        "fec_birthday": "2022-03-29T13:20:05.602Z",
        "id": "3"
    },
    "3":{
        "fec_alta": "2022-03-08T12:33:32.643Z",
        "user_name": "Lonie85",
        "codigo_zip": "50853",
        "credit_card_num": "6767-1997-9307-1857",
        "credit_card_ccv": "107",
        "cuenta_numero": "35431462",
        "direccion": "Brakus Isle",
        "geo_latitud": "11.4957",
        "geo_longitud": "55.9517",
        "color_favorito": "azure",
        "foto_dni": "http://placeimg.com/640/480",
        "ip": "156.89.51.113",
        "auto": "Jaguar Mercielago",
        "auto_modelo": "XC90",
        "auto_tipo": "Sedan",
        "auto_color": "Chevrolet Malibu",
        "cantidad_compras_realizadas": 39524,
        "avatar": "https://cdn.fakercloud.com/avatars/arishi__128.jpg",
        "fec_birthday": "2022-03-29T14:44:48.206Z",
        "id": "4"
        }
}
"""

df = pd.read_json(data, orient="index")
df

# Parámetros de conexión de la base de datos de SQL Server
server = 'Nombre del servidor'
database = 'Nombre de la base de datos'
username = 'Nombre de usuario'
password = 'Su contraseña'

# Crear una conexión al servidor SQL
conn = pyodbc.connect(
    f'DRIVER={{SQL Server}};'
    f'SERVER={server};'
    f'DATABASE={database};'
    f'UID={username};'
    f'PWD={password};'
)

# Insertar el DataFrame en la base de datos.
df.to_sql(name='Nombre de la tabla', con=conn, if_exists='replace', index=False)

# Crea un cursor para ejecutar una consulta SQL en la tabla que deseas compartir
cursor = conn.cursor()
query = "SELECT * FROM TablaEjemplo"
cursor.execute(query)

# Recuperar resultados de la consulta
results = cursor.fetchall()

# Parámetros de conexión SFTP
sftp_host = 'sftp_server_hostname'
sftp_port = 22
sftp_user = 'tu_usuario_sftp'
sftp_password = 'tu_contraseña_sftp'

# Ruta y nombre del archivo que se creará en el servidor SFTP
remote_filepath = '/ruta/remoto/nombre_archivo.csv'

# Conéctese al servidor SFTP
with pysftp.Connection(host=sftp_host, username=sftp_user, password=sftp_password, port=sftp_port) as sftp:
    # Convertir los resultados de la consulta a un archivo CSV
    csv_data = '\n'.join([','.join(map(str, row)) for row in results])

    # Cargue el archivo CSV al servidor SFTP
    sftp.putfo(io.StringIO(csv_data), remote_filepath)

# Cerrar el cursor y la conexión SQL.
cursor.close()
conn.close()